gen-cal:
	protoc ./proto/calculator.proto --go_out=./proto --go-grpc_out=./proto --go_opt=module=github.com/Chungbien/udemy-grpc-course/calculator/proto --go-grpc_opt=module=github.com/Chungbien/udemy-grpc-course/calculator/proto
